### ISSUE TITLE
User can view a list of parks..

### ISSUE THREAD

**Issue by bryanvaldovinos** [bryanvaldovinos/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view an entire list of all national parks, with an image, title of park, and address of park.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to scroll up or down the entire list of national parks.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-14 at 11 21 01 AM](https://user-images.githubusercontent.com/103273265/173661416-4b38c34b-b82f-4905-bed4-c28157f8900a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Design the structure of your page using HTML & CSS
- [ ] Input park data manually for now to test how layout and structure will look.
- [ ] Ensure the page looks good on both mobile and desktop.
- [ ] Pull data from the API to populate park information.

  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by bryanvaldovinos** [comment]
https://user-images.githubusercontent.com/103273265/173885953-ac09fe61-9915-4db4-87f3-85b41b1590e3.mov
