### ISSUE TITLE
User can mark a park as visited..

### ISSUE THREAD

**Issue by bryanvaldovinos** [bryanvaldovinos/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to mark a park as visited

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to press a button to confirm they've visited a park before.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-14 at 11 35 08 AM](https://user-images.githubusercontent.com/103273265/173663842-b1cec4f9-384e-4aec-886d-a0c823331691.png)
![Screen Shot 2022-06-14 at 11 35 13 AM](https://user-images.githubusercontent.com/103273265/173663833-963df912-6078-4005-989c-d05fdaa3a5fd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

  - [x] Recreate HTML/CSS for a single list item
  - [x] Include button that will be clicked on to indicate whether park has been visited or not
  - [x] Add styling to the button and layout to ensure button looks good on both mobile and desktop
  - [x] Create elements and set classes accordingly in DOM tree to include button and display as it should
  - [x] Delete HTML/CSS for single item
  - [x] Upon click of button ensure button changes text content and styling to mark park accordingly
  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
